In [84]:
from __future__ import print_function
import torch
import numpy as np

In [38]:
torch.tensor([[5,5],[3,3]])
res = torch.empty(5,5)
torch.add(torch.rand(5,5), torch.rand(5,5), out=res)
a = torch.eye(5)
b = torch.eye(5)
a.add_(b)
a.add_(b)

tensor([[3., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 3.]])

In [57]:
a = torch.rand(5,5)
a

tensor([[0.8217, 0.3682, 0.0575, 0.3932, 0.1108],
        [0.2895, 0.3278, 0.6503, 0.8280, 0.3745],
        [0.8964, 0.0869, 0.1662, 0.7305, 0.2638],
        [0.2287, 0.3422, 0.6910, 0.8304, 0.3002],
        [0.5839, 0.6241, 0.4226, 0.1848, 0.5247]])

In [65]:
a[:,0]

tensor([0.8217, 0.2895, 0.8964, 0.2287, 0.5839])

In [68]:
a.view(-1)

tensor([0.8217, 0.3682, 0.0575, 0.3932, 0.1108, 0.2895, 0.3278, 0.6503, 0.8280,
        0.3745, 0.8964, 0.0869, 0.1662, 0.7305, 0.2638, 0.2287, 0.3422, 0.6910,
        0.8304, 0.3002, 0.5839, 0.6241, 0.4226, 0.1848, 0.5247])

In [77]:
a = torch.rand(4,5)
a.view(10,2)

tensor([[0.8923, 0.8368],
        [0.7983, 0.7152],
        [0.2163, 0.9078],
        [0.2308, 0.6515],
        [0.8263, 0.1508],
        [0.9419, 0.0998],
        [0.9788, 0.6916],
        [0.5205, 0.6308],
        [0.0159, 0.0932],
        [0.8546, 0.2733]])

In [79]:
a.size()

torch.Size([4, 5])

In [82]:
a

tensor([[0.8923, 0.8368, 0.7983, 0.7152, 0.2163],
        [0.9078, 0.2308, 0.6515, 0.8263, 0.1508],
        [0.9419, 0.0998, 0.9788, 0.6916, 0.5205],
        [0.6308, 0.0159, 0.0932, 0.8546, 0.2733]])

In [83]:
a.numpy()

array([[0.892284  , 0.8367827 , 0.7982987 , 0.71522516, 0.21627808],
       [0.9078297 , 0.2308135 , 0.6515364 , 0.8262927 , 0.15077609],
       [0.94189125, 0.09979522, 0.97877645, 0.6915623 , 0.5204805 ],
       [0.63084775, 0.01590854, 0.09315592, 0.85459226, 0.27331948]],
      dtype=float32)

In [87]:
x = np.eye(5)
torch.from_numpy(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)

In [90]:
torch.cuda.is_available()

False